config/routes.rb
Sparya::Application.routes.draw do
  resources :books

  root to: 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :description, :mirror_links, :publisher, :source, :title, :year, :upload1, :upload2, :license

  has_attached_file :upload1
  has_attached_file :upload2

  after_initialize do
    self.license = "This work is in the public domain in India because its term of copyright has expired." unless self.license
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "manoj", password: "sparya678"

  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= simple_form_for(@book, html: { multipart: true }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, as: :string, input_html: { class: 'input-xxlarge' }
    = f.input :author, as: :string, input_html: { class: 'input-xxlarge' }
    = f.input :year, as: :string, input_html: { class: 'input-xxlarge' }
    = f.input :publisher, as: :string, input_html: { class: 'input-xxlarge' }
    = f.input :description, as: :text, input_html: { rows: 15, cols: 60, class: 'input-xxlarge' }
    = f.input :source, as: :text, input_html: { rows: 8, cols: 60, class: 'input-xxlarge' }
    = f.input :mirror_links, as: :text, input_html: { rows: 10, cols: 60, class: 'input-xxlarge' }
    = f.input :license, as: :text, input_html: { rows: 6, cols: 60, class: 'input-xxlarge' }

    = f.label 'Upload 1'
    = f.file_field :upload1
    .clearfix
    %br
    = f.label 'Upload 2'
    = f.file_field :upload2

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Cancel', root_path, class: 'btn'

app/views/books/edit.html.haml
.container
  .row
    .span8.offset1
      %h3 Edit book
      = render 'form'

app/views/books/index.html.haml
.container
  .row
    .span12
      %h3
        Books
        = link_to '(Add new)', new_book_path, style: 'font-size: 16px'
      %br
      .row
        .span5
          %h4 Title
        .span3
          %h4 Author
      - @books.each do |book|
        .well.row
          .span5
            = link_to book.title, book
          .span3
            %p=book.author
          .span2
            = link_to 'edit', edit_book_path(book)
            |
            = link_to 'delete', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/books/new.html.haml
.container
  .row
    .span8.offset1
      %h3 New book
      = render 'form'

app/views/books/show.html.haml
.container
  .row
    .span10
      .pull-right
        = link_to 'edit', edit_book_path(@book)
        |
        = link_to 'delete', @book, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %br
      - @book.attributes.each do |key, value|
        - unless ['id', 'created_at', 'updated_at'].include? key or key.start_with?('upload')
          .book-item
            .row
              .span9
                %span.book-item-before= key.capitalize
                %p= @book.send(key).html_safe

      - ['upload1', 'upload2'].each do |key|
        - if @book.send(key).exists?
          .book-item
            .row
              .span9
                %span.book-item-before= key.capitalize
                = link_to "#{@book.send(key + '_file_name')} (download)", @book.send(key).url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sparya</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='span5'>
        <h2><%= link_to 'Sparya', root_path %></h2>
      </div>
    </div>
  </div>
<%= yield %>

</body>
</html>